version: '3.7'

services:
  ca-org1:
    image: hyperledger/fabric-ca:1.4.9
    container_name: ca-org1
    networks:
      - test
    labels:
      service: hyperledger-fabric
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS=0.0.0.0:17054
    ports:
      - "7054:7054"
      - "17054:17054"
    volumes:
      - ./organizations/fabric-ca/org1:/etc/hyperledger/fabric-ca-server

networks:
  test:
    name: fabric_test