version: '3.7'

services:
  orderer:
    image: hyperledger/fabric-orderer:2.3
    container_name: orderer
    networks:
      - test
    labels:
      service: hyperledger-fabric
    environment:
      - CONFIGTX_ORDERER_ADDRESSES=orderer:7050
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=Org1MSP
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - ORDERER_GENERAL_LOCALMSPDIR=/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/system-genesis-block/genesis.block
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:9444
    volumes:
      - ./system-genesis-block:/system-genesis-block
      - ./organizations:/organizations
      - orderer:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7053:7053
      - 9444:9444

  peer0-org1:
    container_name: peer0-org1
    image: hyperledger/fabric-peer:2.3
    networks:
      - test
    labels:
      service: hyperledger-fabric
    command: peer node start
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:7061
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      - CORE_PEER_ID=peer0-org1
      - CORE_PEER_ADDRESS=peer0-org1:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0-org1:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0-org1:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0-org1:7051
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
      - CORE_PEER_MSPCONFIGPATH=/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./organizations:/organizations
      - ./chaincode:/opt/gopath/src/github.com/chaincode
      - ./external-builder/detect:/builders/external/bin/detect
      - ./external-builder/build:/builders/external/bin/build
      - ./external-builder/release:/builders/external/bin/release
      - ./external-builder/core.yaml:/etc/hyperledger/fabric/core.yaml
      - peer0-org1:/var/hyperledger/production
    ports:
      - 7051:7051
      - 9443:9443

  cli-peer0-org1:
    container_name: cli-peer0-org1
    depends_on:
      - peer0-org1
    networks:
      - test
    image: hyperledger/fabric-tools:2.3
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    working_dir: /
    environment:
      - ORDERER_CA=/organizations/peerOrganizations/org1.example.com/msp/tlscacerts/ca.crt
      - CORE_PEER_ADDRESS=peer0-org1:7051
      - CORE_PEER_ID=cli.peer0.org1.example.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
      - CORE_PEER_TLS_CERT_FILE=/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      - FABRIC_LOGGING_SPEC=INFO
      - GOPATH=/opt/gopath
      - SYS_CHANNEL=system-channel
      - CORE_CHAINCODE_BUILDER=hyperledger/fabric-ccenv:1.4.8
      - CHANNEL_NAME=mychannel
      - CHAINCODE_NAME=basic
      - CHAINCODE_VERSION=1.0
      - ORDERER_URL=orderer:7050
    volumes:
      - ./organizations:/organizations
      - ./configtx:/configtx
      - ./channel-artifacts:/channel-artifacts
      - ./chaincode:/opt/gopath/src/github.com/chaincode
      - ./scripts:/scripts
      - ./connection-profile:/connection-profile

  basic-org1:
    container_name: basic-org1
    networks:
      - test
    image: suayb/basic-cc-hlf:1.0
    labels:
      service: hyperledger-fabric
    environment:
      - CHAINCODE_ID=basic:35478980dc38b87771c3dd752ef9bc263ac5ce9785d0f1843641f88a1869b730
      - CHAINCODE_SERVER_ADDRESS=0.0.0.0:7052
    ports:
      - 7052:7052

volumes:
  orderer:
    name: orderer
  peer0-org1:
    name: peer0-org1

networks:
  test:
    name: fabric_test